import { platformTokens } from "../tokens/platformTokens"

export type ThemeVars = Record<`--${string}`, string>

export function getPlatformCssVars(): ThemeVars {
    return {
        "--layout-container-max-width": `${platformTokens.layout.containerMaxWidth}px`,
        "--layout-section-spacing": `${platformTokens.layout.sectionSpacing}px`,
        "--space-xs": `${platformTokens.spacing.xs}px`,
        "--space-sm": `${platformTokens.spacing.sm}px`,
        "--space-md": `${platformTokens.spacing.md}px`,
        "--space-lg": `${platformTokens.spacing.lg}px`,
        "--space-xl": `${platformTokens.spacing.xl}px`,
        "--space-xxl": `${platformTokens.spacing.xxl}px`,
        "--breakpoint-sm": `${platformTokens.breakpoints.sm}px`,
        "--breakpoint-md": `${platformTokens.breakpoints.md}px`,
        "--breakpoint-lg": `${platformTokens.breakpoints.lg}px`,
        "--breakpoint-xl": `${platformTokens.breakpoints.xl}px`,
        "--breakpoint-xxl": `${platformTokens.breakpoints.xxl}px`,
        "--radius-sm": `${platformTokens.radius.sm}px`,
        "--radius-md": `${platformTokens.radius.md}px`,
        "--radius-lg": `${platformTokens.radius.lg}px`,
        "--radius-pill": `${platformTokens.radius.pill}px`,
        "--shadow-card": platformTokens.shadow.card,
        "--shadow-floating": platformTokens.shadow.floating,
        "--border-subtle": platformTokens.border.subtle,
        "--border-default": platformTokens.border.default,
        "--border-strong": platformTokens.border.strong,
        "--border-error": platformTokens.border.error,
        "--component-button-height": `${platformTokens.component.button.height}px`,
        "--component-badge-height": `${platformTokens.component.badge.height}px`,
        "--component-input-height": `${platformTokens.component.input.height}px`,
        "--component-card-padding": `${platformTokens.component.card.padding}px`,
        "--state-hover-overlay": platformTokens.state.hoverOverlay,
        "--state-pressed-overlay": platformTokens.state.pressedOverlay,
        "--state-disabled-bg": platformTokens.state.disabledBg,
        "--state-disabled-text": platformTokens.state.disabledText,
        "--status-pending": platformTokens.status.pending,
        "--status-preparing": platformTokens.status.preparing,
        "--status-ready": platformTokens.status.ready,
        "--status-delivered": platformTokens.status.delivered,
        "--status-failed": platformTokens.status.failed,
        "--status-reconnecting": platformTokens.status.reconnecting,
        "--status-offline": platformTokens.status.offline,
        "--tap-target-min": `${platformTokens.accessibility.tapTargetMin}px`,
        "--focus-ring-width": `${platformTokens.accessibility.focusRingWidth}px`,
        "--focus-ring-offset": `${platformTokens.accessibility.focusRingOffset}px`,
        "--motion-fast": platformTokens.motion.duration.fast,
        "--motion-normal": platformTokens.motion.duration.normal,
        "--motion-slow": platformTokens.motion.duration.slow,
        "--easing-standard": platformTokens.motion.easing.standard,
        "--easing-entrance": platformTokens.motion.easing.entrance,
        "--easing-exit": platformTokens.motion.easing.exit
    }
}
